    Complete Numpy Tutorial

NumPy Top 100 Functions for AI/ML

1. np.array()               → Create NumPy array
2. np.asarray()             → Convert object to array
3. np.zeros()               → Create array of zeros
4. np.ones()                → Create array of ones
5. np.empty()               → Create empty array
6. np.full()                → Fill array with one value
7. np.eye()                 → Identity matrix
8. np.identity()            → Identity matrix
9. np.arange()              → Create sequence
10. np.linspace()           → Evenly spaced values
11. np.logspace()           → Log spaced values
12. np.geomspace()          → Geometrically spaced values

13. np.shape()              → Get shape
14. np.ndim()               → Number of dimensions
15. np.size()               → Total elements
16. np.dtype()              → Data type
17. np.reshape()            → Change shape
18. np.resize()             → Resize array
19. np.flatten()            → Flatten copy
20. np.ravel()              → Flatten view
21. np.transpose()          → Transpose array
22. np.swapaxes()           → Swap axes
23. np.expand_dims()        → Add dimension
24. np.squeeze()            → Remove dimension

25. np.concatenate()        → Join arrays
26. np.stack()              → Stack arrays
27. np.vstack()             → Vertical stack
28. np.hstack()             → Horizontal stack
29. np.dstack()             → Depth stack
30. np.column_stack()       → Stack as columns
31. np.row_stack()          → Stack as rows

32. np.split()              → Split array
33. np.array_split()        → Flexible split
34. np.vsplit()             → Vertical split
35. np.hsplit()             → Horizontal split
36. np.dsplit()             → Depth split

37. np.sum()                → Sum of elements
38. np.mean()               → Average
39. np.median()             → Median
40. np.std()                → Standard deviation
41. np.var()                → Variance
42. np.min()                → Minimum
43. np.max()                → Maximum
44. np.argmin()             → Index of minimum
45. np.argmax()             → Index of maximum
46. np.prod()               → Product
47. np.cumsum()             → Cumulative sum
48. np.cumprod()            → Cumulative product
49. np.percentile()         → Percentile
50. np.quantile()           → Quantile

51. np.add()                → Addition
52. np.subtract()           → Subtraction
53. np.multiply()           → Multiplication
54. np.divide()             → Division
55. np.power()              → Power
56. np.sqrt()               → Square root
57. np.square()             → Square
58. np.abs()                → Absolute value
59. np.exp()                → Exponential
60. np.log()                → Natural log
61. np.log10()              → Base-10 log
62. np.sin()                → Sine
63. np.cos()                → Cosine
64. np.tan()                → Tangent
65. np.round()              → Round values
66. np.floor()              → Floor values
67. np.ceil()               → Ceiling values

68. np.where()              → Conditional selection
69. np.nonzero()            → Non-zero indices
70. np.count_nonzero()      → Count non-zero values
71. np.unique()             → Unique values
72. np.sort()               → Sort array
73. np.argsort()            → Indices after sorting
74. np.searchsorted()       → Search insertion index
75. np.isin()               → Membership test

76. np.copy()               → Deep copy
77. np.copyto()             → Copy values
78. np.clip()               → Limit values
79. np.repeat()             → Repeat elements
80. np.tile()               → Repeat array
81. np.diag()               → Create diagonal
82. np.diagonal()           → Extract diagonal
83. np.triu()               → Upper triangle
84. np.tril()               → Lower triangle

85. np.dot()                → Dot product
86. np.matmul()             → Matrix multiplication
87. np.inner()              → Inner product
88. np.outer()              → Outer product
89. np.cross()              → Cross product
90. np.trace()              → Matrix trace
91. np.linalg.inv()         → Matrix inverse
92. np.linalg.det()         → Determinant
93. np.linalg.eig()         → Eigenvalues & Eigenvectors
94. np.linalg.solve()       → Solve linear equations
95. np.linalg.norm()        → Vector/Matrix norm

96. np.random.seed()        → Set random seed
97. np.random.rand()        → Uniform random numbers
98. np.random.randn()       → Normal random numbers
99. np.random.randint()     → Random integers
100. np.random.choice()     → Random sampling

In [1]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Shubham Kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

    An instance of ndarray class can be constructed by different array creation routines described 
    later in the tutorial. The basic ndarray is created using an array function in NumPy as follows: 
                                          numpy.array

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

    With the help of this array we can do multiple matimatical equation and getting the results

In [7]:
np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0) 

array(<class 'object'>, dtype=object)

In [9]:
np.array([1, 2, 3, 4, 5] , dtype = str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [14]:
np.array([1, 2, 3, 4, 5],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [10]:
arr = np.array([10,20,30], ndmin=3)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[10 20 30]]]
3
(1, 1, 3)


In [12]:
arr = np.array([1,2,3,4], ndmin=6)

In [13]:
arr

array([[[[[[1, 2, 3, 4]]]]]])

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

In [18]:
arr.shape

(2, 4)

In [25]:
# an array of evenly spaced numbers 

a = np.arange(0,25,2)

In [26]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [30]:
# this is one dimensional array  
a = np.arange(24) 
a.ndim 
 
# now reshape it 
b = a.reshape(2,4,3) 
# b is having three dimensions

In [31]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [ ]:
b.ndim

3

In [33]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
x = [1,2,3]

y = np.asarray(x)

In [36]:
y

array([1, 2, 3])

In [37]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [39]:
np.random.rand(100, 100)

array([[0.00654833, 0.78527977, 0.77885037, ..., 0.23790608, 0.27478321,
        0.24183357],
       [0.56694784, 0.87681579, 0.19982977, ..., 0.07083572, 0.72717851,
        0.79226577],
       [0.64711514, 0.88132622, 0.04120776, ..., 0.85351985, 0.0261067 ,
        0.82298896],
       ...,
       [0.59091743, 0.48045878, 0.11553565, ..., 0.3382592 , 0.63234524,
        0.56399612],
       [0.73936832, 0.7391505 , 0.71868771, ..., 0.14534767, 0.14821322,
        0.8535157 ],
       [0.39747593, 0.77517027, 0.48579131, ..., 0.47559991, 0.51239415,
        0.94640578]], shape=(100, 100))

In [46]:
np.random.randint(1,100,(4,4))

array([[94, 16, 91,  9],
       [18, 88, 96, 64],
       [54, 47, 71, 59],
       [11, 75, 14,  7]], dtype=int32)

In [43]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.size)#size will return the number of elements in the array

print(arr.shape)#shape will return the shape of the array

print(arr.ndim)#ndim will return the number of dimensions of the array

print(arr.dtype)#dtype will return the data type of the array

print(arr.T)#T will return the transpose of the array -- i hope it will be important in future

print(arr.reshape(2,3))#reshape will return the reshaped array

print(arr.flatten())#flatten will return the flattened array

print(arr.tolist())#tolist will return the list of the array

arr = np.array([[1,2,3],
                [4,5,6]])

6
(2, 3)
2
int64
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1, 2, 3], [4, 5, 6]]


In [44]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
arr = np.array([1, 2, 3, 4])

arr.reshape(2, 2)

array([[1, 2],
       [3, 4]])

In [49]:
arr.flatten()

array([1, 2, 3, 4])

In [50]:
arr.T

array([1, 2, 3, 4])

In [51]:
np.transpose(np.array([[1,2,3],[4,5,6]]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [52]:
#you can arith anything like + , - , * , / , ** , etc

In [57]:
a = np.array([[1],[2],[3]])
print(a.ndim)


b = np.array([10,20,30])

print(b.ndim)

res = a+b
print(res.ndim)
print(res)

2
1
2
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [59]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [60]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

np.cross(A, B)

C:\Users\Shubham Kumar\AppData\Local\Temp\ipykernel_23320\1719862434.py:7: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(A, B)


array([-4, -4])

In [61]:
np.sort(np.random.randn(10))

array([-1.14208787, -0.45240259, -0.33059979, -0.27072629,  0.07778207,
        0.16084945,  0.38975064,  0.40950285,  0.56800503,  0.88000325])

    Numpy in stats

In [62]:
arr

array([1, 2, 3, 4])

In [63]:
np.mean(arr)

np.float64(2.5)

In [64]:
np.median(arr)

np.float64(2.5)

In [67]:
np.std(arr) #standard deviation

np.float64(1.118033988749895)

In [68]:
np.var(arr)

np.float64(1.25)

In [69]:
np.min(arr)

np.int64(1)

In [71]:
np.max(arr)

np.int64(4)

In [73]:
np.sum(arr)

np.int64(10)

In [74]:
np.unique(arr)

array([1, 2, 3, 4])

In [76]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([[1, 2, 3], [4, 5, 6]])

In [77]:
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [79]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [80]:
np.split(a,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [81]:
np.where(arr>5)

(array([], dtype=int64),)

In [82]:
np.all(arr>10)

np.False_

In [83]:
np.save("data.npy", arr)

In [84]:
np.load("data.npy")

array([1, 2, 3, 4])

In [85]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [86]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [87]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [88]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [89]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

    Linear Algebra

In [91]:
A = np.array([[1,2],
              [3,4]]) 

In [92]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [93]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [94]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

In [95]:
np.linalg.matrix_rank(A)

np.int64(2)

In [96]:
np.linalg.eig(A)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [97]:
np.linalg.norm(A)

np.float64(5.477225575051661)

In [ ]:
#This is Z-score normalization, commonly used before training algorithms like Logistic Regression, SVM, and Neural Networks.

X = np.array([10, 20, 30, 40, 50])

X_scaled = (X - np.mean(X)) / np.std(X)

X_scaled

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [100]:
weights = np.array([0.5, 1.2, -0.7])
features = np.array([2, 4, 1])

prediction = np.dot(weights, features)

print(prediction)

5.1
