    Complete Numpy Tutorial

In [1]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Shubham Kumar\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

    An instance of ndarray class can be constructed by different array creation routines described 
    later in the tutorial. The basic ndarray is created using an array function in NumPy as follows: 
                                          numpy.array

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

    With the help of this array we can do multiple matimatical equation and getting the results

In [7]:
np.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0) 

array(<class 'object'>, dtype=object)

In [9]:
np.array([1, 2, 3, 4, 5] , dtype = str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [14]:
np.array([1, 2, 3, 4, 5],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [10]:
arr = np.array([10,20,30], ndmin=3)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[10 20 30]]]
3
(1, 1, 3)


In [12]:
arr = np.array([1,2,3,4], ndmin=6)

In [13]:
arr

array([[[[[[1, 2, 3, 4]]]]]])

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

In [18]:
arr.shape

(2, 4)

In [25]:
# an array of evenly spaced numbers 

a = np.arange(0,25,2)

In [26]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])